use_frameworks!

platform :ios, '11.0'

target 'HTMapKit_Example' do
  pod 'HTMapKit', :path => '../'

  target 'HTMapKit_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
end
